# github actions的yml配置文件
name: updateCFDns
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone 。+8才是北京时间，每天凌晨1点17
    - cron: '17 17 * * *'
  watch:
    types: started

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    # 定时，或者自己点击star则运行此workflow
    if: github.event_name == 'schedule' || github.event_name == 'watch' && github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: start run
        env:
          EMAIL: ${{ secrets.EMAIL }}
          GLOBAL_KEY: ${{ secrets.GLOBAL_KEY }}
          ZONE_ID: ${{ secrets.ZONE_ID }}
          DOMAIN: ${{ secrets.DOMAIN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python src/change_CF_DNS.py

